import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Button } from "react-bootstrap";
import Web3Modal from "web3modal";
import React, { useEffect, setState } from "react";
import BuyModal from "../components/BuyModal";
import { ethers } from "ethers";

import { checkWalletConnection, connectWallet, sendUSDC } from "./wallet.js";

export default function Home() {
  const [ethersProvider, setEthersProvider] = React.useState(null);
  const [connectedAccounts, setConnectedAccounts] = React.useState([]);
  const [walletAddress, setWalletAddress] = React.useState(null);
  const [selectedPrice, setSelectedPrice] = React.useState(null);

  useEffect(() => {
    checkWalletConnection().then((res) => {
      setEthersProvider(res.provider);
      setConnectedAccounts(res.accounts);
      if (res.accounts.length > 0) {
        setWalletAddress(res.accounts[0]);
      } else {
        setWalletAddress(null);
      }
    });
  }, []);

  console.log("Render: Home");

  const coffeePrice = 0.5;

  return (
    <div className={styles.container}>
      <Head>
        <title>Optimistic Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.titleGradient}>OPTIMISTIC CAFÉ</h1>
        <img href="https://storage.googleapis.com/isometriclove.appspot.com/tea_S_1k.gif" />

        {connectedAccounts.length == 0 && (
          <div className="top-nav">
            <Button
              onClick={() => {
                connectWallet().then((res) => {
                  setEthersProvider(res.provider);
                  setConnectedAccounts(res.accounts);
                });
              }}
              className="connect-btn"
              variant="warning"
            >
              🔌 Connect wallet
            </Button>
          </div>
        )}

        {ethersProvider && connectedAccounts > 0 && (
          <div className={styles.grid}>
            {/* TODO: generate in a loop with randomized prices */}
            <a
              className={styles.card}
              onClick={() => {
                localStorage.setItem("selectedPrice", 2.4);
              }}
            >
              <img
                src="https://cdn2.iconfinder.com/data/icons/coffee-19/451/affogato-1024.png"
                style={{ width: "50px" }}
              ></img>
              <h5>Chad Macchiato</h5>
              <p>2.4 USDC</p>

              <BuyModal
                provider={ethersProvider}
                accountAddress={connectedAccounts[0]}
              />
            </a>

            <a
              className={styles.card}
              onClick={() => {
                localStorage.setItem("selectedPrice", 0.5);
              }}
            >
              <img
                src="https://cdn2.iconfinder.com/data/icons/coffee-19/442/tea-1024.png"
                style={{ width: "50px" }}
              ></img>
              <h5>Ape Espresso</h5>
              <p>{coffeePrice} USDC</p>

              <BuyModal
                provider={ethersProvider}
                accountAddress={connectedAccounts[0]}
              />
            </a>
            <a
              className={styles.card}
              onClick={() => {
                localStorage.setItem("selectedPrice", 4.6);
              }}
            >
              <img
                src="https://cdn2.iconfinder.com/data/icons/coffee-19/448/coffee_cup-1024.png"
                style={{ width: "50px" }}
              ></img>
              <h5>Whale Latte</h5>

              <p>4.60 USDC</p>

              <BuyModal
                provider={ethersProvider}
                accountAddress={connectedAccounts[0]}
              />
            </a>
            <a
              className={styles.card}
              onClick={() => {
                localStorage.setItem("selectedPrice", 7.3);
              }}
            >
              <img
                src="https://cdn2.iconfinder.com/data/icons/coffee-19/443/Cappuccino-1024.png"
                style={{ width: "50px" }}
              ></img>
              <h5>Degen Cappuccino</h5>
              <p>7.30 USDC</p>

              <BuyModal
                provider={ethersProvider}
                accountAddress={connectedAccounts[0]}
              />
            </a>
          </div>
        )}
      </main>
    </div>
  );
}
